name: Build - Windows
description: 'Build Windows release'

runs:
  using: "composite"
  steps:
  - name: Build miner
    run: dotnet publish miner --configuration Release --self-contained -r win-x64 -p:PublishReadyToRun=true --output publish/miner/${{ inputs.runtime }}
    shell: powershell
