name: Build - Windows
description: 'Build Windows release'

runs:
  using: "composite"
  steps:
  - name: Build miner
    run: dotnet publish miner --configuration Release --self-contained -r win-x64 -p:PublishReadyToRun=true --output publish/miner/${{ inputs.runtime }}
    shell: powershell
 
 - name: Package zip
   working-directory: publish/miner/${{ inputs.runtime }}
   run: zip -r "miner${{ env.VERSION }}.zip" *
   shell: powershell
   
- name: Copy artifacts
    working-directory: publish/miner/${{ inputs.runtime }}
    run: move-item miner${{ env.VERSION }}.zip ${{ github.workspace }}
    shell: powershell
